### ISSUE TITLE
Update to Jupyter

### ISSUE THREAD

**Issue by josh-gree** [facebook/iTorch#33] opened 2015-03-05 12:39 UTC
Having updated ipython notebook to the new Jupyter incarnation I am no longer able to run Itorch notebooks. I get the following error in the terminal;

[E 12:31:50.348 NotebookApp] Bad kernel_info reply
    Traceback (most recent call last):
      File "/Users/jdg1g14/anaconda/lib/python2.7/site-packages/IPython/html/services/kernels/handlers.py", line 136, in _handle_kernel_info_reply
        msg = self.session.deserialize(msg)
      File "/Users/jdg1g14/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 826, in deserialize
        raise ValueError("Unsigned Message")
    ValueError: Unsigned Message
[C 12:31:50.355 NotebookApp] Malformed message: ['<IDS|MSG>', '', '{"session":"cbb297c0-14a9-46bc-c691-1d0ef9b42df9","date":"2015-03-05T12:31:50","username":"itorch","msg_id":"efce62cb-11ae-47cc-c783-b28c18a61233","msg_type":"kernel_info_reply"}', '{"version":"5.0","session":"2C78A94C43AD4D938328AA5F64DF5483","username":"username","msg_id":"8B1711ABA13643C68B62C682142D0937","msg_type":"kernel_info_request"}', '{}', '{"protocol_version":[4,0],"language":"lua","language_version":[20100]}']
    Traceback (most recent call last):
      File "/Users/jdg1g14/anaconda/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 181, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jdg1g14/anaconda/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 162, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/jdg1g14/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 826, in deserialize
        raise ValueError("Unsigned Message")
    ValueError: Unsigned Message
/Users/jdg1g14/torch/install/bin/luajit: /Users/jdg1g14/torch/install/share/lua/5.1/itorch/main.lua:256: attempt to index local 'line' (a nil value)
stack traceback:
	/Users/jdg1g14/torch/install/share/lua/5.1/itorch/main.lua:256: in function 'extract_completions'
	/Users/jdg1g14/torch/install/share/lua/5.1/itorch/main.lua:297: in function </Users/jdg1g14/torch/install/share/lua/5.1/itorch/main.lua:295>
	/Users/jdg1g14/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	...s/jdg1g14/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	...s/jdg1g14/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	...s/jdg1g14/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/Users/jdg1g14/torch/install/share/lua/5.1/itorch/main.lua:341: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x010ec41640

Any help would be appreciated...

**Comment by soumith** [comment] 2015-03-05 14:08
hey Josh, I have not yet tested this with Jupyter. I will test it and get back to you today. thanks for the report

**Comment by rezakhorshidi** [comment] 2015-03-10 17:21
Hi @soumith / @josh-gree 
Any luck with this? I can't run the old notebooks (cant see their contents even), after update to Jupyter.

**Comment by soumith** [comment] 2015-03-10 18:13
i've reproduced the issue. will prepare appropriate fixes this week/weekend.

**Comment by rezakhorshidi** [comment] 2015-03-17 08:08
Hi  @soumith
Not sure if the issue has been fixed, but I am using the latest anaconda (incl. IPython) distribution, and have installed iTorch again. Torch works, IPython works, but iTorch doesn't work (neither in notebook nor in terminal). Any thoughts on what could be causing this?

**Comment by soumith** [comment] 2015-03-26 05:05
Sorry for the delay. I've fixed it via this commit: https://github.com/facebook/iTorch/commit/59be6bcaf64f737a2361158b3021923e1afde39f

All you have to do to get it working with IPython 3.0 is do:
```
luarocks install itorch
```

And then to start itorch in notebook mode:
```
itorch notebook
```
And then create a new iTorch notebook from dropdown menu.

starting `ipython notebook` wont work, starting `itorch notebook` will work.
I am looking to see how `ipython notebook` will also work in 3.0.
If after this reinstall, you are still having trouble in ipython v3.0, please reopen this issue.

**Comment by rezakhorshidi** [comment] 2015-03-26 15:14
Thanks @soumith - really appreciate this.
I doesn't seem to be working for me.
When I start a torch notebook, this is the error I see (in the terminal):

[E 15:12:16.297 NotebookApp] Bad kernel_info reply
    Traceback (most recent call last):
      File "/Users/rezakhorshidi/anaconda/lib/python2.7/site-packages/IPython/html/services/kernels/handlers.py", line 136, in _handle_kernel_info_reply
        msg = self.session.deserialize(msg)
      File "/Users/rezakhorshidi/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 826, in deserialize
        raise ValueError("Unsigned Message")
    ValueError: Unsigned Message
[C 15:12:16.301 NotebookApp] Malformed message: ['<IDS|MSG>', '', '{"session":"cbb297c0-14a9-46bc-c691-1d0ef9b42df9","date":"2015-03-26T15:12:16","username":"itorch","msg_id":"efce62cb-11ae-47cc-c783-b28c18a61233","msg_type":"kernel_info_reply"}', '{"version":"5.0","session":"F863A9700B4B4E5F9A52E30DCE650117","username":"username","msg_id":"615D8039001B427D8E8A682E62E1C465","msg_type":"kernel_info_request"}', '{}', '{"protocol_version":[4,0],"language":"lua","language_version":[20100]}']
    Traceback (most recent call last):
      File "/Users/rezakhorshidi/anaconda/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 181, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/rezakhorshidi/anaconda/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 162, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/rezakhorshidi/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 826, in deserialize
        raise ValueError("Unsigned Message")
    ValueError: Unsigned Message




Any thoughts?

**Comment by josh-gree** [comment] 2015-03-26 15:21
Thanks for this but again not working for me, don't get any error in the
terminal output but new notebook starts with an unaccessible cell. Could
this possibly be an anaconda issue?

Josh

**Comment by soumith** [comment] 2015-03-26 15:34
@rezakhorshidi i see the error that you see if I start "ipython notebook" and choose "new -> iTorch". if I start "itorch notebook", I dont see the error. Regardless, spending some time today to fix this even more properly.

**Comment by rezakhorshidi** [comment] 2015-03-26 15:38
I see ...
Well, I use 
    itorch notebook
in the terminal to open the server and start a notebook and this happens.
Moreover, if I simply use
    itorch 
and open it in the terminal, it functions as an ipython shell (i.e., import numpy works, but require 'nn' doesn't).

**Comment by iassael** [comment] 2015-03-26 16:10
@soumith works like a charm for me with "itorch notebook" and creating a new one. Thank you!

**Comment by rezakhorshidi** [comment] 2015-03-26 16:30
@iassael what can be the possible cause on my side? Are you using anaconda (i)python?

**Comment by iassael** [comment] 2015-03-26 17:10
@rezakhorshidi yes I am using the latest Anaconda Python. I don't know if it was necessary or they were overwritten in any case but removed any torch ~/.ipython configurations, and then reinstalled iTorch using luarocks make. Finally, everything works perfect when I use "itorch notebook" from terminal.

**Comment by thealch3m1st** [comment] 2015-03-26 22:45
I installed torch for the first time yesterday and I had all sorts of issues when trying to run itorch notebook. All my issues were fixed by changing the last line in~/torch/install/bin/itorch from:

`ipython $mode --profile torch $@`
to:
`ipython $mode --MappingKernelManager.default_kernel_name="itorch" --Session.key='' $@`
This gets rid of the need for the torch python profile (I couldn't get it to work just by modifying the profile, also the profile uses `c.KernelManager.kernel_cmd` which is deprecated)
Only the kernel_spec is needed - `~/./ipython/kernels/itorch/kernel.json`.

**Comment by soumith** [comment] 2015-03-26 22:49
@thealch3m1st are you some kind of a wizard? Where does one find documentation for all of these command-line flags...
Let me try this and patch it in master.

**Comment by soumith** [comment] 2015-03-26 23:08
@rezakhorshidi fixed it more properly in trunk, thanks to @thealch3m1st. See if "itorch notebook" now works for you.
https://github.com/facebook/iTorch/commit/8a6d29faf2bd9e4c5edea0cab14ae1a08462d3f3

**Closed by soumith** 2015-03-26 23:08 UTC
Labels: bug

**Comment by soumith** [comment] 2015-03-26 23:09
@rezakhorshidi you will have to reinstall itorch ("luarocks install itorch")

**Comment by thealch3m1st** [comment] 2015-03-27 00:38
@soumith I'm new to iPython & torch. I went thru hours of researching and trial and error before I got to what I posted. 

This explains how to use the command line flags:
https://ipython.org/ipython-doc/dev/config/intro.html#command-line-arguments

I found the `--MappingKernelManager.default_kernel_name` option while looking thru all the commented options in the profile trying to find a replacement for deprecated `c.KernelManager.kernel_cmd`. The kernel wasn't starting at all for me whenever I opened a notebook and the notebook (even if it had content) looked empty. I was just looking for a way to force it to start the iTorch kernel, but changing stuff in the profile didn't really work for me so I looked for a way to set options one by one using the command line and found the info in the link above. 

`--Session.key=''` disables auth/encryption and fixes the `ValueError("Unsigned Message")` exception when running without the profile (it's being set in the profile, so without the profile the option is not set).

**Comment by soumith** [comment] 2015-03-27 00:51
@thealch3m1st thanks for doing all that research. It looks like the ipython guys are in a transition, because your solution works for itorch notebook, but not for itorch console (pushed another fix for that).

I was lost on how to set the session key to empty string in the new 3.0 configuration (I already do it with the 2.0 config).

**Comment by rezakhorshidi** [comment] 2015-03-27 15:02
Thanks @soumith and @thealch3m1st 
It works perfectly fine now.

**Comment by Ashutosh1995** [comment] 2017-08-14 19:20
I have installed all the dependencies like ipython, iTorch and Jupyter. But when I run jupyter notebook, I am not able to see itorch notebook.

Please suggest any solution @soumith !!
