### ISSUE TITLE
[osx 10.10] Could not satisfy dependency: env

### ISSUE THREAD

**Issue by jaidevd** [facebook/iTorch#8] opened 2015-01-17 08:22 UTC
Hi!

It seems there's some package called env which is a dependency of iTorch.
(https://github.com/facebook/iTorch/blob/master/itorch-scm-1.rockspec#L23)

I cannot locate this package on moonrocks or the torch server. Where can I find it?

Thanks a lot!

**Comment by soumith** [comment] 2015-01-17 08:24
It's a package in the torch rocks server: https://github.com/torch/rocks/blob/master/env-scm-1.rockspec
luarocks install env 
should work.

**Comment by jaidevd** [comment] 2015-01-17 08:27
`$ luarocks install env` doesn't work for me, just says:

Error: No results matching query were found.

However, I can just install using the rockspec file, right?

**Comment by soumith** [comment] 2015-01-17 08:30
yes, you can install using:
luarocks install https://raw.githubusercontent.com/torch/rocks/master/env-scm-1.rockspec

however, it's not a good sign that luarocks does not see the manifest.
this typically happens if you installed your own luarocks outside of the torch install. in that case, you might have to specify "luarocks --server=https://raw.github.com/torch/rocks/master install [package]"

**Comment by jaidevd** [comment] 2015-01-17 08:35
Yes, that's exactly what happened. The installation is working now. 
But now the kernel keeps dying when I launch the notebook. Here's the traceback...

```
2015-01-17 14:03:32.034 [NotebookApp] Using existing profile dir: u'/Users/jaidevd/.ipython/profile_torch'
2015-01-17 14:03:32.041 [NotebookApp] Using MathJax from CDN: http://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-01-17 14:03:32.074 [NotebookApp] Serving notebooks from local directory: /Users/jaidevd
2015-01-17 14:03:32.074 [NotebookApp] 0 active kernels
2015-01-17 14:03:32.074 [NotebookApp] The IPython Notebook is running at: http://localhost:8888/
2015-01-17 14:03:32.074 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).                                                                    [15/1079]
2015-01-17 14:03:36.969 [NotebookApp] Creating new notebook in /
2015-01-17 14:03:36.971 [NotebookApp] Writing notebook-signing key to /Users/jaidevd/.ipython/profile_torch/security/notebook_secret
INFO:tornado.access:302 GET /notebooks/custom.css (::1) 0.50ms
WARNING:tornado.access:404 GET /files/custom.css (::1) 0.82ms referer=http://localhost:8888/notebooks/Untitled0.ipynb
2015-01-17 14:03:37.839 [NotebookApp] Kernel started: 50281f6a-73b8-4548-b886-95480cf5df0a
/usr/local/bin/luajit: (command line):1: module 'itorch.IOHandler' not found:
        no field package.preload['itorch.IOHandler']
        no file './itorch/IOHandler.lua'
        no file '/usr/local/share/luajit-2.0.2/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler/init.lua'
        no file './itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './itorch.so'
        no file '/usr/local/lib/lua/5.1/itorch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x0104b42d50
2015-01-17 14:03:40.842 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 50281f6a-73b8-4548-b886-95480cf5df0a restarted
/usr/local/bin/luajit: (command line):1: module 'itorch.IOHandler' not found:
        no field package.preload['itorch.IOHandler']
        no file './itorch/IOHandler.lua'
        no file '/usr/local/share/luajit-2.0.2/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler/init.lua'
        no file './itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './itorch.so'
        no file '/usr/local/lib/lua/5.1/itorch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x010a6ebd50
2015-01-17 14:03:43.851 [NotebookApp] KernelRestarter: restarting kernel (2/5)
/usr/local/bin/luajit: (command line):1: module 'itorch.IOHandler' not found:
        no field package.preload['itorch.IOHandler']
        no file './itorch/IOHandler.lua'
        no file '/usr/local/share/luajit-2.0.2/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler/init.lua'
        no file './itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './itorch.so'
        no file '/usr/local/lib/lua/5.1/itorch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x0104b42d50
2015-01-17 14:03:40.842 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 50281f6a-73b8-4548-b886-95480cf5df0a restarted
/usr/local/bin/luajit: (command line):1: module 'itorch.IOHandler' not found:
        no field package.preload['itorch.IOHandler']
        no file './itorch/IOHandler.lua'
        no file '/usr/local/share/luajit-2.0.2/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler/init.lua'
        no file './itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './itorch.so'
        no file '/usr/local/lib/lua/5.1/itorch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x010a6ebd50
2015-01-17 14:03:43.851 [NotebookApp] KernelRestarter: restarting kernel (2/5)
/usr/local/bin/luajit: (command line):1: module 'itorch.IOHandler' not found:
        no field package.preload['itorch.IOHandler']
        no file './itorch/IOHandler.lua'
        no file '/usr/local/share/luajit-2.0.2/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler.lua'
        no file '/usr/local/share/lua/5.1/itorch/IOHandler/init.lua'
        no file './itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/itorch/IOHandler.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './itorch.so'
        no file '/usr/local/lib/lua/5.1/itorch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x0109f0ad50
2015-01-17 14:03:46.424 [NotebookApp] Kernel shutdown: 50281f6a-73b8-4548-b886-95480cf5df0a
^C2015-01-17 14:04:07.596 [NotebookApp] interrupted
Serving notebooks from local directory: /Users/jaidevd
0 active kernels
The IPython Notebook is running at: http://localhost:8888/
Shutdown this notebook server (y/[n])? y
2015-01-17 14:04:09.200 [NotebookApp] CRITICAL | Shutdown confirmed
2015-01-17 14:04:09.200 [NotebookApp] Shutting down kernels
```

**Comment by soumith** [comment] 2015-01-17 08:43
the issue is again probably stemming from the non-standard luarocks install. one of two things happened:
1. itorch was installed by the "other" luarocks into a different location than what the torch install expects.
2. itorch did not get installed succesfully, and there might have been an error emmitted at "luarocks install itorch".

Either ways, I would recommend you to stop here and just remove the system luarocks, and use the luajit+luarocks shipped with torch.

**Comment by jaidevd** [comment] 2015-01-17 08:46
Thanks. Will try that out.

**Comment by soumith** [comment] 2015-01-17 08:53
thanks, i'm going to close this issue, as we cant support non-standard lua setups, as we cant reproduces issues.

**Closed by soumith** 2015-01-17 08:53 UTC
